name: Fix MinGW
description: Fix MinGW 

# inputs:
# outputs:

runs:
  using: composite
  steps:
    - name: Add to beginning of PATH
      shell: pwsh
      run: |
        [regex]::Matches($env:PATH, "[^;]+mingw[^;]+") | % Value >> $env:GITHUB_PATH

branding:
  icon: alert-circle
  color: green
